setono_sylius_loyalty_admin_account:
    resource: |
        alias: setono_sylius_loyalty.account
        section: admin
        templates: "@SyliusAdmin\\Crud"
        only: ['index']
        grid: setono_sylius_loyalty_admin_account
        vars:
            all:
                subheader: setono_sylius_loyalty.ui.manage_loyalty_accounts
    type: sylius.resource
